jobs:
  include:
    - stage: test
      name: "Backend using Python"
      language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
        - pip install pytest
        - pip install codecov
        - pip install pytest-cov
      script:
        - pytest --cov-report term --cov=backend backend/UnitTests/ 
      after_success: 
        - codecov
    - stage: test
      name: "Frontend using React"
      language: node.js
      node_js: 14
      cache:
        directories:
          - node_modules
      script:
        - npm install
        - npm test
    - stage: sonarcloud
      name: "SolarCloud Scan"
      addons:
        sonarcloud:
          organization: "smartcast"
          token:
            secure: "dcYLT3Wp1DdvAlx+iNuSgp/afNBM7vjtYB+7joKJzAvmKW48IsLnsTvNGPJUo1WnUGh0oXRcfDzkaKsaWIsLu++XjZveY+sDKgFSib01yj7+C05E4b9UvF+OZLWsLoWIuIYfOQNPkODS3fmOb08roQyuFfRLGIcKVS+NLrQRrVvxJiTg9syG89baAsKFcplomWLl1psbt3ma4IrBb8F0GMKYctgW4Jztp1lZcXqdsvRFomkyf5QhEhadp8H6gWZ6RWrPZ634LqRGPOyi6Q7tO64rLEvbtUNcxWkfZN45M5vXnXuHNC8E2knsLA4PN6nc7w1K/eLKwtg9BLuLKBs8+W7DJTdkGiloK4O/4ik5yQ1pLaQ3fUENaH5hfiu8o6+bzWTq0w9eg3zE7osxBqjsZSwjq0RFRfbdwcuKlPzvnlU4OjfpBuXOIoUjHO60YJJk9/kNPeaju+yCRVMcdWK7pvb3iAqguivRB6LLr5opBOELtLnm+xBgLb+Cm5GtkBahh7G6Pxmv8F1m16xz5JkePWioHHmM8NF2FapycNgxlo7RRQmZTNq/Mn/0z9owrd+X0OPEtUl6k1dd6Ic2i3WO6aiwAPY0yPDva5j1hQ7cEen9HGxczmc5OetT07+X8gzfkDyzF/h1GzDMqjhlFQaMRs6KoO4lNvDJ0LaE8dAyW9o="
      script:
        - sonar-scanner