matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
      before_script:
        - cd backend/UnitTests
      script:
        - pytest
    - language: node.js
      node_js: 14
      cache:
        directories:
          - node_modules
      script:
        - npm install
        - npm test -- --code-coverage

addons:
  sonarcloud:
    organization: "smartcast"
    token:
      secure: SONAR_TOKEN
script:
  - sonar-scanner