matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
        - pip install pytest
        - pip install codecov
        - pip install pytest-cov
      before_script:
        - cd backend/UnitTests
      script:
        - pytest --cov-report term --cov=investpy
      after_success: 
        - codecov
    - language: node.js
      node_js: 14
      cache:
        directories:
          - node_modules
      script:
        - npm install
        - npm test -- --code-coverage

addons:
  sonarcloud:
    organization: "smartcast"
    token:
      secure: SONAR_TOKEN
script:
  - sonar-scanner